### ISSUE TITLE
Start creating unity tests

### ISSUE THREAD

**Issue by vitorestevam** [VitorEstevam/FluentRequest#2]
By now we only have a single test doing a request. We need to create a structure to make easier for the mainteners to create new cases. Probably using table driven tests would be a good option to keep it simple, but robust.

a few links as reference:
https://yourbasic.org/golang/table-driven-unit-test/
https://www.codementor.io/@cyantarek15/how-table-driven-tests-makes-writing-unit-tests-exciting-and-fun-in-go-15g1wzdf7g
https://dev.to/boncheff/table-driven-unit-tests-in-go-407b

**Comment by ArmoryNode** [comment]
If no one is currently working on this one, I can take a look at it 🙂
